name: Build and vercel deploy

on:
  workflow_run:
    workflows:
      - Lint and test
    types:
      - completed

permissions:
  contents: read

concurrency:
  group: 'vercel-deploy'
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build-and-vercel-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and vercel deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Build
        run: |
          npx vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Vercel deploy
        run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
